### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pkpp1233** [blockspring/blockspring.py#6]
Use ran `pip install blockspring` and got the following error on Mac + Python 2.7
```
Collecting blockspring
/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached blockspring-0.1.10-py2.py3-none-any.whl
Collecting requests (from blockspring)
  Using cached requests-2.7.0-py2.py3-none-any.whl
Installing collected packages: requests, blockspring
  Exception:
  Traceback (most recent call last):
    File "/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg/pip/basecommand.py", line 246, in main
      status = self.run(options, args)
    File "/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg/pip/commands/install.py", line 352, in run
      root=options.root_path,
    File "/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg/pip/req/req_set.py", line 693, in install
      **kwargs
    File "/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg/pip/req/req_install.py", line 817, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg/pip/req/req_install.py", line 1018, in move_wheel_files
      isolated=self.isolated,
    File "/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg/pip/wheel.py", line 237, in move_wheel_files
      clobber(source, lib_dir, True)
    File "/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg/pip/wheel.py", line 208, in clobber
      os.makedirs(destdir)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
      mkdir(name, mode)
  OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/requests'
```

Was fixed when they ran with sudo.

**Comment by jjangsangy** [comment]
It looks like the user is using the Framework Python.

Simple fix without the need to use sudo would be to run with user flag.

```
pip install --user blockspring
```

The proper fix would be to install python using homebrew. I've written up some documentation on how to get this done [here](http://pythonhosted.org/py-translate/users/install_osx.html)
